// tfarSettings.sqf

TF_GIVE_MICRODAGR_TO_SOLDIER = false;
TF_SAME_LR_FREQUENCIES_FOR_SIDE = true;
TF_SAME_SW_FREQUENCIES_FOR_SIDE = true;
TF_TERRAIN_INTERCEPTION_COEFFICIENT = 6.0;

publicVariable "TF_GIVE_MICRODAGR_TO_SOLDIER";
publicVariable "TF_SAME_LR_FREQUENCIES_FOR_SIDE";
publicVariable "TF_SAME_SW_FREQUENCIES_FOR_SIDE";
publicVariable "TF_TERRAIN_INTERCEPTION_COEFFICIENT";
